### ISSUE TITLE
Caching not working in prod

### ISSUE THREAD

**Issue by marpa** [clas-web/word-cloud#1]
Caching was working fine in dev, but is not working in prod.  When the "cache post count" button is clicked, a counter is displayed and increments but when complete it return:

> No complete cache found.
> false

**Comment by marpa** [comment]
The word_cloud_cache arrays in prod have an invalid datetime, compare:

dev word_cloud_cache array
`a:3:{s:8:"settings";a:4:{s:10:"post_types";a:1:{i:0;s:10:"connection";}s:10:"taxonomies";a:1:{i:0;s:15:"connection-link";}s:17:"filterby_taxonomy";s:16:"connection-group";s:14:"filterby_terms";s:12:"anthropology";}s:8:"datetime";s:19:"2016-09-05 01:55:38";`

prod word_cloud_cache array
`a:3:{s:8:"settings";a:4:{s:10:"post_types";a:1:{i:0;s:10:"connection";}s:10:"taxonomies";a:1:{i:0;s:15:"connection-link";}s:17:"filterby_taxonomy";s:16:"connection-group";s:14:"filterby_terms";s:4:"chhs";}s:8:"datetime";N;`

**Comment by atrus1701** [comment]
Did you update the APL in production?  This may have no effect, but I did make some changes to APL when I ran into a similar bug.

**Comment by marpa** [comment]
Hi Crystal,
Thanks for your quick reply.  Updating APL in prod fixed word cloud caching
issues.  The Word Cloud cached version is still breaking the D3 version.
Both versions had been working in dev, but not in prod.  Now both versions
are also not working in dev either, see:
https://github.com/clas-web/word-cloud/issues/2

Some versions of the D3 Word cloud plugin have a widgets.php, some also
have an admin-pages folder, which version should be used?

Thanks for any help you can provide.
Alex

**Comment by marpa** [comment]
Caching has been fixed by updating the APL plugin.  For issues with breaking the D3 version, see:https://github.com/clas-web/word-cloud/issues/2
